- README.md
- src/src/Vis/visEngine.jsx
> fix problem, that vis is not loading if a single widget has a script error

- README.md
- src/src/Attributes/Widget/WidgetField.jsx
> fix crash when selecting multiple widgets

- README.md
- src/src/Vis/visBaseWidget.jsx
> fix crash when reordering widgets

- README.md
- src/package.json
> update adapter-react to have enhanced image support in file selector

- README.md
- src/src/App.jsx
> improved performance due to optimizations on auto save

- README.md
- src/src/Attributes/Widget/index.jsx
- src/src/Components/CustomAceEditor.jsx
> fix overlap between pipette and binding icon buttons

- README.md
- package.json
- src/src/Components/MaterialIconSelector.jsx
> fixed issues with icon selector filter when changing category

- README.md
- src/src/App.jsx
- src/src/Attributes/Widget/WidgetBindingField.js
- src/src/Toolbar/MultiSelect.js
- multiselect has shown object object instead of name if one was shown with a real name span
- closes #140
> fix problem when multiple widgets are selected

- src/src/App.jsx
> page names are no longer shown as uppercase

- src/src/Vis/Widgets/JQui/JQuiButton.jsx
> do not force uppercase on JQUIButton widgets

- src/src/Attributes/Widget/index.jsx
> fix editing groups

- README.md
- src/src/Toolbar/ProjectsManager/index.jsx
> respect uppercase/lowercase in projects toolbar

- README.md
- src/src/Toolbar/ViewsManager/index.jsx
> sort view alphabetically

- README.md
- src/src/Vis/visView.jsx
> fixed crash case when editing group

- README.md
- src/src/Toolbar/ViewsManager/index.jsx
> also sort folders alphabetically

- README.md
- src/src/Toolbar/ViewsManager/index.jsx
- src/src/Vis/visBaseWidget.jsx
> fixed deselecting widgets with ctrl + click

- README.md
- src/src/Runtime.jsx
- src/src/Vis/visEngine.jsx
- src/src/types.d.ts
> fixed problem with open/close dialog via state

- README.md
- src/src/Toolbar/ProjectsManager/index.jsx
- src/src/Toolbar/ViewsManager/index.jsx
- src/src/Vis/visEngine.jsx
- src/src/Vis/visView.jsx
> sort pages and projects alphabetically

- README.md
- src/src/App.jsx
- src/src/Utils/utils.tsx
> fixed issue on saving

- README.md
- src/src/App.jsx
- src/src/Utils/utils.tsx
> enabled pasting group to another view

- README.md
- src/src/bootstrap.jsx
> fixed theme also being applied inside an iFrame

- README.md
- src/src/App.jsx
- src/src/Attributes/Widget/WidgetField.jsx
> fixed reactivity in custom components

- README.md
- src/.eslintrc.js
- src/package.json
- src/src/App.jsx
- src/src/Toolbar/WidgetImportDialog.jsx
- src/src/Vis/Widgets/Basic/BasicScreenResolution.tsx
- src/src/Vis/Widgets/Basic/BasicSvgShape.tsx
> fixed import for groups

- README.md
- src/src/Vis/visView.jsx
> recalc fields when widget moved via keyboard

- README.md
- src/src/App.jsx
> after creating a group it is now pre-selected

- README.md
- src/src/Attributes/View.jsx
- src/src/Vis/utils.tsx
- src/src/Vis/visNavigation.jsx
- src/src/i18n/de.json
- src/src/i18n/en.json
- src/src/i18n/es.json
- src/src/i18n/fr.json
- src/src/i18n/it.json
- src/src/i18n/nl.json
- src/src/i18n/pl.json
- src/src/i18n/pt.json
- src/src/i18n/ru.json
- src/src/i18n/uk.json
- src/src/i18n/zh-cn.json
> implemented simple sort mechanic for navigation

- README.md
- src/src/App.jsx
- src/src/Toolbar/ViewsManager/ViewDialog.tsx
- src/src/Toolbar/ViewsManager/index.jsx
- src/src/Utils.tsx
- src/src/Utils/utils.tsx
> do not simply reuse widget ids, when importing or copying views

- README.md
- src/public/widgets/basic.html
- src/src/Vis/Widgets/Basic/BasicBulb.tsx
- src/src/Vis/Widgets/index.jsx
- src/src/Vis/utils.tsx
- src/src/types.d.ts
> implemented basic bulb widget as react widget

- README.md
- src/src/App.jsx
> open new views at the beginning

- README.md
- src/src/Vis/Widgets/Basic/BasicBulb.tsx
> BasicBulb treat empty string in same logic as undefined previously

- README.md
- src/src/Vis/visBaseWidget.jsx
- src/src/Vis/visRxWidget.tsx
> prevent short flashing of widgets with visibility condition at page load

- README.md
- src/src/App.jsx
- src/src/Vis/visView.jsx
> fixed issue when switching themes

- README.md
- src/src/App.jsx
- src/src/Vis/Widgets/Basic/BasicBulb.tsx
> make BasicBulb behave more like its old version

- README.md
- src/src/Vis/visRxWidget.tsx
> fixed bug with visibility calculation

- README.md
- src/src/Vis/Widgets/JQui/JQuiState.jsx
> fix crash when multiple JquiState widgets selected

- README.md
- src/src/Vis/visUtils.jsx
> correctly detect IDs in bindings when they contain hash character

- README.md
- src/src/Vis/visFormatUtils.jsx
> clarify binding documentation by providing an example

- README.md
- src/src/Vis/Widgets/JQui/JQuiState.jsx
- src/src/Vis/visBaseWidget.jsx
> fixed issue where JquiState did not respect data type

- README.md
- src/src/Vis/oldVis.jsx
- src/src/Vis/visBaseWidget.jsx
- src/src/Vis/visCanWidget.jsx
> fixed last change y-offset for some widgets

- README.md
- src/src/App.jsx
- src/src/Vis/Widgets/JQui/BulkEditor.tsx
> implemented workaround resize bug for https://github.com/devbookhq/splitter/issues/15

- README.md
- src/src/Vis/Widgets/JQui/BulkEditor.tsx
> fixed issue with BulkEditor

- README.md
- src/src/App.jsx
> fixed issue, that old attributes value is shown in some scenarios

- README.md
- src/src/Vis/visBaseWidget.jsx
- src/src/Vis/visBaseWidget.tsx
- src/src/Vis/visRxWidget.tsx
- src/src/types.d.ts
> fixed issue when resizing widget from the left side

- README.md
- src/src/Toolbar/ProjectsManager/PermissionsDialog.tsx
- src/src/Toolbar/ProjectsManager/index.jsx
- src/src/Utils.tsx
- src/src/Utils/utils.tsx
- src/src/Vis/visView.jsx
- src/src/types.d.ts
> added widget permissions to permissions dialog

- README.md
- src/src/Vis/visBaseWidget.tsx
> fixed bug, that opacity is applied twice on image edit mode overlay

- README.md
- src/src/Components/WizardHelpers.jsx
- src/src/Vis/oldVis.jsx
- src/src/Vis/visBaseWidget.tsx
- src/src/Vis/visCanWidget.jsx
- src/src/Vis/visEngine.jsx
- src/src/Vis/visRxWidget.tsx
- src/src/Vis/visUtils.jsx
- closes https://github.com/ioBroker/ioBroker.vis-2/issues/322
> fixed crash case when fixing widgets 

- README.md
- src/public/widgets/basic.html
- src/src/Vis/Widgets/Basic/BasicImage8.tsx
- src/src/Vis/Widgets/index.jsx
> Image 8 widget ported to react

- README.md
- src/src/Attributes/Widget/WidgetField.jsx
- src/src/Vis/visRxWidget.tsx
> do not crash when using visibility 'only for groups'

- README.md
- src/public/widgets/basic.html
- src/src/Vis/Widgets/Basic/BasicImage8.tsx
- src/src/Vis/visWidgetsCatalog.jsx
> fixed issue, that Basic Image 8 is not configurable for 0 value

- README.md
- src/src/Attributes/View.jsx
- src/src/Runtime.jsx
- src/src/Vis/visNavigation.jsx
- src/src/i18n/de.json
- src/src/i18n/en.json
- src/src/i18n/es.json
- src/src/i18n/fr.json
- src/src/i18n/it.json
- src/src/i18n/nl.json
- src/src/i18n/pl.json
- src/src/i18n/pt.json
- src/src/i18n/ru.json
- src/src/i18n/uk.json
- src/src/i18n/zh-cn.json
> navigation style fixes (fix icon background and allow to customize header text color)

- README.md
- io-package.json
- src/package.json
> allow to disable sentry only for instance

- README.md
- src/src/Vis/visBaseWidget.tsx
- src/src/Vis/visRxWidget.tsx
> fixed issue with signals on RxWidgets

- README.md
- src/src/Vis/visUtils.jsx
> fixed crash case for broken grouped widgets

- README.md
- src/src/Vis/visEngine.jsx
> user-specified css has now priority over widgets css

- README.md
- src/src/Vis/Widgets/JQui/JQuiInputDate.tsx
- src/src/Vis/visFormatUtils.jsx
- src/src/i18n/de.json
- src/src/i18n/en.json
- src/src/i18n/es.json
- src/src/i18n/fr.json
- src/src/i18n/it.json
- src/src/i18n/nl.json
- src/src/i18n/pl.json
- src/src/i18n/pt.json
- src/src/i18n/ru.json
- src/src/i18n/uk.json
- src/src/i18n/zh-cn.json
- and made default option of Date Picker human readable and added option for full parseable date
- closes #391
> fixed various problems with Date Picker widget

- README.md
- src/src/Attributes/Widget/WidgetBindingField.jsx
- src/src/Vis/visFormatUtils.jsx
> allow to use widget oid in bindings

- packages/iobroker.vis-2/src-vis/src/Attributes/View.tsx
- packages/iobroker.vis-2/src-vis/src/Attributes/View/Items.tsx
- packages/types-vis-2/index.d.ts
fix [bug]: Benutzer definierte Auflösung kann man nicht einstellen #506
> fix [bug]: Benutzer definierte Auflösung kann man nicht einstellen #506

- packages/iobroker.vis-2/src-vis/src/Vis/Widgets/Basic/BasicViewInWidget8.tsx
- packages/iobroker.vis-2/src-vis/src/Vis/visEngine.tsx
- packages/iobroker.vis-2/src-vis/src/Vis/visRxWidget.tsx
- packages/iobroker.vis-2/src-vis/src/Vis/visUtils.tsx
@GermanBluefox I haven't found a cleaner solution to notify rxWidgets, maybe you know how to achieve it in a cleaner fashion
see also https://github.com/ioBroker/ioBroker.vis-2/issues/18
> enable local binding states for rxWidgets like ViewInWidget8
